{% set name = "gis-metadata-parser" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gis-metadata-parser-{{ version }}.tar.gz
  sha256: 752cf78b3b51cfedf51e374e6d0fc5521fe74309094715dd31d82a7495e0c801

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - frozendict >=2.0,<3.0
    - parserutils >=2.0.1,<3.0.0
    - python >={{ python_min }},<4.0

test:
  imports:
    - gis_metadata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/consbio/gis-metadata-parser/
  summary: Parser for GIS metadata standards including ArcGIS, FGDC and ISO-19115
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dharvey-consbio
    - jlaura
